name: NVM
description: Annotates the build with a file count
author: https://github.com/automattic
requirements: []
configuration:
  properties:
    version:
      type: string
  additionalProperties: false
