name: NVM
description: Sets up Node.js environment using nvm
author: https://github.com/automattic
requirements: []
configuration:
  properties:
    version:
      type: string
  additionalProperties: false
