steps:
  - command: make validate

  - label: ":node: Validate {{ matrix.node }} via version property"
    command: .buildkite/verify_node.sh {{ matrix.node }}
    plugins:
      - automattic/nvm#${BUILDKITE_COMMIT}:
          version: "{{ matrix.node }}"
    env:
      IMAGE_ID: xcode-14.3.1
    agents:
      queue: "{{ matrix.queue }}"
    matrix:
      setup:
        node:
          # node v18 and later don't work on the current build agent.
          # Once we switch to a newer OS for the default agent, we can add more node
          # versions here. See https://github.com/nvm-sh/nvm/issues/2972
          - v17
          - v16
        queue:
          - mac
          - default

  - label: ":node: Do nothing when no .nvmrc and no node version specified"
    command: echo noop
    plugins:
      - automattic/nvm#${BUILDKITE_COMMIT}

  # More details on what is being test here can be found at
  # https://github.com/Automattic/nvm-buildkite-plugin/pull/9
  - label: ":node: [Test] source nvm from npm script"
    command: cd tests/dummy && npm install
    plugins:
      - automattic/nvm#${BUILDKITE_COMMIT}:
          version: v17
    env:
      IMAGE_ID: xcode-14.3.1
    agents:
      queue: "{{ matrix.queue }}"
    matrix:
      setup:
        queue:
          - mac
          - default

  - label: ":node: [Test] curlrc option"
    command: cd tests/dummy && npm install
    plugins:
      - automattic/nvm#${BUILDKITE_COMMIT}:
          version: v17
          curlrc: --verbose
    env:
      IMAGE_ID: xcode-14.3.1
    agents:
      queue: "{{ matrix.queue }}"
    matrix:
      setup:
        queue:
          - mac
          - default
